/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef LCMETRICTABLE_H
#define LCMETRICTABLE_H

/* function declarations */
netsnmp_tdata* init_lcMetricTable(void);
netsnmp_tdata* initialize_table_lcMetricTable(void);
Netsnmp_Node_Handler lcMetricTable_handler;

/* column number definitions for table lcMetricTable */
       #define COLUMN_LCCUSTOMERINDEX		1
       #define COLUMN_LCSITEINDEX		2
       #define COLUMN_LCDEVICEINDEX		3
       #define COLUMN_LCCONTAINERINDEX		4
       #define COLUMN_LCOBJECTINDEX		5
       #define COLUMN_LCMETRICINDEX		6
       #define COLUMN_LCMETRICNAME		7
       #define COLUMN_LCMETRICDESC		8
       #define COLUMN_LCMETRICADMINSTATUS		9
       #define COLUMN_LCMETRICOPERSTATUS		10
       #define COLUMN_LCMETRICCURVALUE		11
       #define COLUMN_LCMETRICCURVALUERAW		12



/* Typical data structure for a row entry */
struct lcMetricTable_entry {
    /* Index values */
    u_long lcCustomerIndex;
    u_long lcSiteIndex;
    u_long lcDeviceIndex;
    u_long lcContainerIndex;
    u_long lcObjectIndex;
    u_long lcMetricIndex;

    /* Column values */
    char *lcMetricName;
    size_t lcMetricName_len;
    char *lcMetricDesc;
    size_t lcMetricDesc_len;
    long lcMetricAdminStatus;
    long lcMetricOperStatus;
    char *lcMetricCurValue;
    size_t lcMetricCurValue_len;
    char *lcMetricCurValueRaw;
    size_t lcMetricCurValueRaw_len;

    int   valid;
};

netsnmp_tdata_row *
lcMetricTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                 , u_long  lcSiteIndex
                 , u_long  lcDeviceIndex
                 , u_long  lcContainerIndex
                 , u_long  lcObjectIndex
                 , u_long  lcMetricIndex
                );

netsnmp_tdata* lcMetricTable ();


#endif /* LCMETRICTABLE_H */
