/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef LCOBJECTTABLE_H
#define LCOBJECTTABLE_H

/* function declarations */
netsnmp_tdata* init_lcObjectTable(void);
netsnmp_tdata* initialize_table_lcObjectTable(void);
Netsnmp_Node_Handler lcObjectTable_handler;

/* column number definitions for table lcObjectTable */
       #define COLUMN_LCCUSTOMERINDEX		1
       #define COLUMN_LCSITEINDEX		2
       #define COLUMN_LCDEVICEINDEX		3
       #define COLUMN_LCCONTAINERINDEX		4
       #define COLUMN_LCOBJECTINDEX		5
       #define COLUMN_LCOBJECTNAME		6
       #define COLUMN_LCOBJECTDESC		7
       #define COLUMN_LCOBJECTADMINSTATUS		8
       #define COLUMN_LCOBJECTOPERSTATUS		9



/* Typical data structure for a row entry */
struct lcObjectTable_entry {
    /* Index values */
    u_long lcCustomerIndex;
    u_long lcSiteIndex;
    u_long lcDeviceIndex;
    u_long lcContainerIndex;
    u_long lcObjectIndex;

    /* Column values */
    char lcObjectName[256];
    size_t lcObjectName_len;
    char lcObjectDesc[256];
    size_t lcObjectDesc_len;
    long lcObjectAdminStatus;
    long lcObjectOperStatus;

    int   valid;
};

netsnmp_tdata_row *
lcObjectTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                 , u_long  lcSiteIndex
                 , u_long  lcDeviceIndex
                 , u_long  lcContainerIndex
                 , u_long  lcObjectIndex
                );

netsnmp_tdata* lcObjectTable ();


#endif /* LCOBJECTTABLE_H */
