/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef LCSITETABLE_H
#define LCSITETABLE_H

/* function declarations */
netsnmp_tdata* init_lcSiteTable(void);
netsnmp_tdata* initialize_table_lcSiteTable(void);
Netsnmp_Node_Handler lcSiteTable_handler;

/* column number definitions for table lcSiteTable */
       #define COLUMN_LCCUSTOMERINDEX		1
       #define COLUMN_LCSITEINDEX		2
       #define COLUMN_LCSITENAME		3
       #define COLUMN_LCSITEDESC		4
       #define COLUMN_LCSITEADMINSTATUS		5
       #define COLUMN_LCSITEOPERSTATUS		6



/* Typical data structure for a row entry */
struct lcSiteTable_entry {
    /* Index values */
    u_long lcCustomerIndex;
    u_long lcSiteIndex;

    /* Column values */
    char lcSiteName[256];
    size_t lcSiteName_len;
    char lcSiteDesc[256];
    size_t lcSiteDesc_len;
    long lcSiteAdminStatus;
    long lcSiteOperStatus;

    int   valid;
};

netsnmp_tdata_row *
lcSiteTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                 , u_long  lcSiteIndex
                );

netsnmp_tdata* lcSiteTable ();


#endif /* LCSITETABLE_H */
