/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "lcTriggerTable.h"

static netsnmp_tdata *static_lcTriggerTable = NULL;

/** Pointer retrieval */
netsnmp_tdata* lcTriggerTable ()
{ return static_lcTriggerTable; }

/** Initializes the lcTriggerTable module */
netsnmp_tdata*
init_lcTriggerTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    return initialize_table_lcTriggerTable();
}

/** Initialize the lcTriggerTable table by defining its contents and how it's structured */
netsnmp_tdata*
initialize_table_lcTriggerTable(void)
{
    static oid lcTriggerTable_oid[] = {1,3,6,1,4,1,20038,1,1,7};
    size_t lcTriggerTable_oid_len   = OID_LENGTH(lcTriggerTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "lcTriggerTable",     lcTriggerTable_handler,
              lcTriggerTable_oid, lcTriggerTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_data = netsnmp_tdata_create_table( "lcTriggerTable", 0 );
    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: lcCustomerIndex */
                           ASN_UNSIGNED,  /* index: lcSiteIndex */
                           ASN_UNSIGNED,  /* index: lcDeviceIndex */
                           ASN_UNSIGNED,  /* index: lcContainerIndex */
                           ASN_UNSIGNED,  /* index: lcObjectIndex */
                           ASN_UNSIGNED,  /* index: lcMetricIndex */
                           ASN_UNSIGNED,  /* index: lcTriggerIndex */
                           0);

    table_info->min_column = COLUMN_LCTRIGGERNAME;
    table_info->max_column = COLUMN_LCTRIGGEROPERSTATUS;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    static_lcTriggerTable = table_data;

    return table_data;
}

/* create a new row in the table */
netsnmp_tdata_row *
lcTriggerTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                 , u_long  lcSiteIndex
                 , u_long  lcDeviceIndex
                 , u_long  lcContainerIndex
                 , u_long  lcObjectIndex
                 , u_long  lcMetricIndex
                 , u_long  lcTriggerIndex
                ) {
    struct lcTriggerTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct lcTriggerTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;
    entry->lcCustomerIndex = lcCustomerIndex;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->lcCustomerIndex),
                                 sizeof(entry->lcCustomerIndex));
    entry->lcSiteIndex = lcSiteIndex;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->lcSiteIndex),
                                 sizeof(entry->lcSiteIndex));
    entry->lcDeviceIndex = lcDeviceIndex;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->lcDeviceIndex),
                                 sizeof(entry->lcDeviceIndex));
    entry->lcContainerIndex = lcContainerIndex;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->lcContainerIndex),
                                 sizeof(entry->lcContainerIndex));
    entry->lcObjectIndex = lcObjectIndex;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->lcObjectIndex),
                                 sizeof(entry->lcObjectIndex));
    entry->lcMetricIndex = lcMetricIndex;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->lcMetricIndex),
                                 sizeof(entry->lcMetricIndex));
    entry->lcTriggerIndex = lcTriggerIndex;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->lcTriggerIndex),
                                 sizeof(entry->lcTriggerIndex));
    netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* remove a row from the table */
void
lcTriggerTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct lcTriggerTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */
    entry = (struct lcTriggerTable_entry *)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    if (entry)
        SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/** handles requests for the lcTriggerTable table */
int
lcTriggerTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct lcTriggerTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct lcTriggerTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_LCTRIGGERNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lcTriggerName,
                                          table_entry->lcTriggerName_len);
                break;
            case COLUMN_LCTRIGGERDESC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lcTriggerDesc,
                                          table_entry->lcTriggerDesc_len);
                break;
            case COLUMN_LCTRIGGERADMINSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lcTriggerAdminStatus);
                break;
            case COLUMN_LCTRIGGEROPERSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lcTriggerOperStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
