/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef LCTRIGGERTABLE_H
#define LCTRIGGERTABLE_H

/* function declarations */
netsnmp_tdata* init_lcTriggerTable(void);
netsnmp_tdata* initialize_table_lcTriggerTable(void);
Netsnmp_Node_Handler lcTriggerTable_handler;

/* column number definitions for table lcTriggerTable */
       #define COLUMN_LCCUSTOMERINDEX		1
       #define COLUMN_LCSITEINDEX		2
       #define COLUMN_LCDEVICEINDEX		3
       #define COLUMN_LCCONTAINERINDEX		4
       #define COLUMN_LCOBJECTINDEX		5
       #define COLUMN_LCMETRICINDEX		6
       #define COLUMN_LCTRIGGERINDEX		7
       #define COLUMN_LCTRIGGERNAME		8
       #define COLUMN_LCTRIGGERDESC		9
       #define COLUMN_LCTRIGGERADMINSTATUS		10
       #define COLUMN_LCTRIGGEROPERSTATUS		11



/* Typical data structure for a row entry */
struct lcTriggerTable_entry {
    /* Index values */
    u_long lcCustomerIndex;
    u_long lcSiteIndex;
    u_long lcDeviceIndex;
    u_long lcContainerIndex;
    u_long lcObjectIndex;
    u_long lcMetricIndex;
    u_long lcTriggerIndex;

    /* Column values */
    char lcTriggerName[256];
    size_t lcTriggerName_len;
    char lcTriggerDesc[256];
    size_t lcTriggerDesc_len;
    long lcTriggerAdminStatus;
    long lcTriggerOperStatus;

    int   valid;
};

netsnmp_tdata_row *
lcTriggerTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                 , u_long  lcSiteIndex
                 , u_long  lcDeviceIndex
                 , u_long  lcContainerIndex
                 , u_long  lcObjectIndex
                 , u_long  lcMetricIndex
                 , u_long  lcTriggerIndex
                );

netsnmp_tdata* lcTriggerTable ();


#endif /* LCTRIGGERTABLE_H */
