/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef LCCONTAINERTABLE_H
#define LCCONTAINERTABLE_H

/* function declarations */
netsnmp_tdata* init_lcContainerTable(void);
netsnmp_tdata* initialize_table_lcContainerTable(void);
Netsnmp_Node_Handler lcContainerTable_handler;

/* column number definitions for table lcContainerTable */
       #define COLUMN_LCCUSTOMERINDEX		1
       #define COLUMN_LCSITEINDEX		2
       #define COLUMN_LCDEVICEINDEX		3
       #define COLUMN_LCCONTAINERINDEX		4
       #define COLUMN_LCCONTAINERNAME		5
       #define COLUMN_LCCONTAINERDESC		6
       #define COLUMN_LCCONTAINERADMINSTATUS		7
       #define COLUMN_LCCONTAINEROPERSTATUS		8



/* Typical data structure for a row entry */
struct lcContainerTable_entry {
    /* Index values */
    u_long lcCustomerIndex;
    u_long lcSiteIndex;
    u_long lcDeviceIndex;
    u_long lcContainerIndex;

    /* Column values */
    char lcContainerName[256];
    size_t lcContainerName_len;
    char lcContainerDesc[256];
    size_t lcContainerDesc_len;
    long lcContainerAdminStatus;
    long lcContainerOperStatus;

    int   valid;
};

netsnmp_tdata_row *
lcContainerTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                 , u_long  lcSiteIndex
                 , u_long  lcDeviceIndex
                 , u_long  lcContainerIndex
                );

netsnmp_tdata* lcContainerTable ();


#endif /* LCCONTAINERTABLE_H */
