/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef LCCUSTOMERTABLE_H
#define LCCUSTOMERTABLE_H

/* function declarations */
netsnmp_tdata* init_lcCustomerTable(void);
netsnmp_tdata* initialize_table_lcCustomerTable(void);
Netsnmp_Node_Handler lcCustomerTable_handler;

/* column number definitions for table lcCustomerTable */
       #define COLUMN_LCCUSTOMERINDEX		1
       #define COLUMN_LCCUSTOMERNAME		2
       #define COLUMN_LCCUSTOMERDESC		3
       #define COLUMN_LCCUSTOMERADMINSTATUS		4
       #define COLUMN_LCCUSTOMEROPERSTATUS		5



/* Typical data structure for a row entry */
struct lcCustomerTable_entry {
    /* Index values */
    u_long lcCustomerIndex;

    /* Column values */
    char lcCustomerName[256];
    size_t lcCustomerName_len;
    char lcCustomerDesc[256];
    size_t lcCustomerDesc_len;
    long lcCustomerAdminStatus;
    long lcCustomerOperStatus;

    int   valid;
};

netsnmp_tdata_row *
lcCustomerTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                );

netsnmp_tdata* lcCustomerTable ();


#endif /* LCCUSTOMERTABLE_H */
