/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef LCDEVICETABLE_H
#define LCDEVICETABLE_H

/* function declarations */
netsnmp_tdata* init_lcDeviceTable(void);
netsnmp_tdata* initialize_table_lcDeviceTable(void);
Netsnmp_Node_Handler lcDeviceTable_handler;

/* column number definitions for table lcDeviceTable */
       #define COLUMN_LCCUSTOMERINDEX		1
       #define COLUMN_LCSITEINDEX		2
       #define COLUMN_LCDEVICEINDEX		3
       #define COLUMN_LCDEVICENAME		4
       #define COLUMN_LCDEVICEDESC		5
       #define COLUMN_LCDEVICEADMINSTATUS		6
       #define COLUMN_LCDEVICEOPERSTATUS		7



/* Typical data structure for a row entry */
struct lcDeviceTable_entry {
    /* Index values */
    u_long lcCustomerIndex;
    u_long lcSiteIndex;
    u_long lcDeviceIndex;

    /* Column values */
    char lcDeviceName[256];
    size_t lcDeviceName_len;
    char lcDeviceDesc[256];
    size_t lcDeviceDesc_len;
    long lcDeviceAdminStatus;
    long lcDeviceOperStatus;

    int   valid;
};

netsnmp_tdata_row *
lcDeviceTable_createEntry(netsnmp_tdata *table_data
                 , u_long  lcCustomerIndex
                 , u_long  lcSiteIndex
                 , u_long  lcDeviceIndex
                );

netsnmp_tdata* lcDeviceTable ();


#endif /* LCDEVICETABLE_H */
