#! /bin/sh

svn co svn+ssh://svn.lithiumcorp.com/sql/svn/actuator/trunk actuator
svn co svn+ssh://svn.lithiumcorp.com/sql/svn/construct/trunk construct
svn co svn+ssh://svn.lithiumcorp.com/sql/svn/induction/trunk induction
svn co svn+ssh://svn.lithiumcorp.com/sql/svn/lithium/trunk lithium
svn co svn+ssh://svn.lithiumcorp.com/sql/svn/mars/trunk mars
svn co svn+ssh://svn.lithiumcorp.com/sql/svn/webmsp/trunk webmsp
svn co svn+ssh://svn.lithiumcorp.com/sql/svn/vendor_xserve/trunk vendor_xserve
svn co svn+ssh://svn.lithiumcorp.com/sql/svn/vendor_xraid/trunk vendor_xraid
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_3com/trunk vendor_3com
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_alliedtelesyn/trunk vendor_alliedtelesyn
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_apcups/trunk vendor_apcups
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_airport/trunk vendor_airport
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_cisco/trunk vendor_cisco
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_foundry/trunk vendor_foundry
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_filer/trunk vendor_filer
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_hp/trunk vendor_hp 
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_icmp/trunk vendor_icmp 
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_infortrend/trunk vendor_infortrend 
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_liebert/trunk vendor_liebert
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_netbotz/trunk vendor_netbotz
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_netsnmp/trunk vendor_netsnmp
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_printer/trunk vendor_printer
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_snmpadv/trunk vendor_snmpadv
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_snmpbasic/trunk vendor_snmpbasic
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_windows/trunk vendor_windows
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_fcswitch/trunk vendor_fcswitch
svn co svn+ssh://oss.lithiumcorp.com/www/svn/vendor_mgeups/trunk vendor_mgeups
