#!/bin/sh
set -e

# Ensure Core is auto-started
update-rc.d lithiumcore defaults

# Restart Core
if which invoke-rc.d >/dev/null 2>&1; then
  invoke-rc.d lithiumcore stop
  invoke-rc.d lithiumcore start
else
  /etc/init.d/lithiumcore stop
  /etc/init.d/lithiumcore start
fi

# Restart Apache
if which invoke-rc.d >/dev/null 2>&1; then
  invoke-rc.d apache2 restart
else
  /etc/init.d/apache2 restart
fi

exit 0
