#!/bin/sh
set -e

update-rc.d lithiumcore defaults

if which invoke-rc.d >/dev/null 2>&1; then
  invoke-rc.d lithiumcore restart
else
  /etc/init.d/lithiumcore restart
fi

WWWPATH="/var/www"
if [ -d "$WWWPATH" ]; then 
    if [ -L "$WWWPATH" ]; then
        # It is a symlink!
        # Symbolic link specific commands go here
        rm "$WWWPATH"
    else
        # It's a directory!
        # Directory command goes here
        rm -rf "$WWWPATH"
    fi
fi
ln -sf /usr/share/htdocs $WWWPATH

if which invoke-rc.d >/dev/null 2>&1; then
  invoke-rc.d apache2 restart
else
  /etc/init.d/apache2 restart
fi


exit 0
